Add automated build and submit pipeline DIP
goatcorp/DIPs pull request #17
Opened 2022-05-03 08:36 UTC by philpax

First DIP, yay!

This is a first draft with a few unanswered questions. I've left them vague so that we can specify them.

Would like input from @ayyaruq and @NotAdam if possible.

2022-05-03 10:39 UTC, NotAdam requested changes

2022-05-03 10:39 UTC, NotAdam commented on text/0000-automated-build-and-submit-pipeline.md
> +This will require all first-party plugin developers to abide by a common project structure that is amenable to being built by CI, and for the code of their plugins to be open-source. The latter is al
probably should have some way of surfacing what's used easily so someone can look and see if there's anything amiss quickly more than anything else

2022-05-03 10:39 UTC, NotAdam commented on text/0000-automated-build-and-submit-pipeline.md
> +An alternative design was proposed by [Ay](https://github.com/ayyaruq) where plugin developers, upon main repo approval, would be given keys exclusive to the plugin that could be used to sign future
i think this is too complicated and not worth it

2022-05-03 10:39 UTC, NotAdam commented on text/0000-automated-build-and-submit-pipeline.md
> +- Should the developer specify the packaging step within their `csproj`, or should we do it for them?
plugin devs should define their plugin metadata in the csproj (basically how dalamudpackager works) and we use the same props

2022-05-03 10:39 UTC, NotAdam commented on text/0000-automated-build-and-submit-pipeline.md
> +- Do we want to automatically approve updates to already-submitted plugins?
depends how much you trust people, but then you can get 1 good release in and then immediately release malware, so lol

2022-05-03 10:39 UTC, NotAdam commented on text/0000-automated-build-and-submit-pipeline.md
> +- As we're building the code, we have an opportunity to analyse it and ensure that it isn't doing anything outright naughty. We would likely use a solution similar to [S&box](https://wiki.facepunch.c
this doesn't account for unsafe code at all, which basically lets you do whatever you want

2022-05-03 11:46 UTC, kalilistic commented on text/0000-automated-build-and-submit-pipeline.md
> +- Do we want to automatically approve updates to already-submitted plugins?
I think an idea before was auto-approving testing plugins but not main.

2022-05-03 11:46 UTC, kalilistic commented on text/0000-automated-build-and-submit-pipeline.md
> +This will require all first-party plugin developers to abide by a common project structure that is amenable to being built by CI, and for the code of their plugins to be open-source. The latter is al
Could review existing plugins to see how many would have significant issues under this.

2022-05-05 17:04 UTC, hedgeye-fslezak commented on text/0000-automated-build-and-submit-pipeline.md
> +When updating a plugin, the developer merely needs to update the `commit` for the metadata file, and make a PR. The previously mentioned steps will take place.
How would this handle changelogs for plugins? For example, I may want to include testing notes or create a "rollup" of my changes, or otherwise diverge from "these are the git commits between these times" as these are often technical and not necessarily good/useful to end users.

2022-05-05 17:04 UTC, KazWolfe commented on text/0000-automated-build-and-submit-pipeline.md
> +When updating a plugin, the developer merely needs to update the `commit` for the metadata file, and make a PR. The previously mentioned steps will take place.
How would this handle changelogs for plugins? For example, I may want to include testing notes or create a "rollup" of my changes, or otherwise diverge from "these are the git commits between these times" as these are often technical and not necessarily good/useful to end users.

2022-05-05 17:10 UTC, NotNite commented on text/0000-automated-build-and-submit-pipeline.md
> +The `repository` refers to a Git repository (not necessarily hosted on Git), and the `commit` refers to a specific commit to build and deploy. For this to work, the repository must be structured to b
"not necessarily hosted on Git" doesn't make much sense - did you mean GitHub here?

2022-05-05 17:25 UTC, NotNite commented
Would a developer be able to test the build process to make sure it works before PRing? One concern of mine is merging a PR and then the plugin build fails in the action. Perhaps we could provide a standalone action runnable through [act](https://github.com/nektos/act), or a Docker container.

~~also can we please make a cool dalamud logo ascii art for the script that'll build the plugins~~

2022-05-05 17:31 UTC, NotNite commented
Also, it should be of note we set up dependencies properly. The script should make sure to clone Git submodules and install NuGet packages. We should also have it post webhooks to `#github` so we'll know if a build is failing.

2022-05-05 17:33 UTC, NotNite commented on text/0000-automated-build-and-submit-pipeline.md
> +    "commit": "7ba9de4049066218f67e260e2c0f8ec0651ffed7"
What about testing? Will it have a separate folder, or a `testing_commit` entry in this file?

2022-05-05 18:03 UTC, karashiiro commented
That shouldn't be an issue, this wouldn't run any plugin code. If the deployed code is a build requirement, that could be done as a build task, but if it's a runtime requirement then it shouldn't matter.

2022-05-05 18:04 UTC, karashiiro commented
Of course, that also partially-undermines the point of this DIP, which is something else to think about.

2022-05-05 19:09 UTC, KazWolfe commented
> if it's a runtime requirement then it shouldn't matter.

I'd tend to agree, but I do want to bring it up because it does add a bit of thought to how/when/why things would be triggered on the Dalamud side for devs of plugins like this. These plugins are more likely to do Other Things™ as well that may cause varying degrees of headaches under the current proposal:

* Both Ava and I place all of our components in our respective repositories. We'd need to have some way to tell the build system which `.csproj` file to use and which to ignore. While a forced repository restructure would work here, I'm hesitant to propose that as a solution.
* It is completely possible for dependencies/other components to require different build environments for one reason or another. The Stream Deck Plugin, for example, builds inside of a Ubuntu GitHub Action. A client/server model may want to build with different dependencies in a different context. I don't think it's reasonable to push these build deps over to Goatcorp, nor require they handle external CI.
* As alluded to, plugins that inherently depend on external things (be they build-time or runtime) already somewhat break the entire point of this DIP. Goatcorp doesn't (can't) know what the library I'm building is doing necessarily, especially if the build is grabbing it from my Releases page in real-time. Similarly, a client-server plugin with a runtime dep can have behavior changed at any time.

If the solution to this problem becomes "trigger your own CI, do whatever you need to do, and then automatically submit a PR once you're ready", that's perfectly acceptable (at least to me). 

> perhaps they could be moved to the "blessed second-party repositories" we've been talking about in a separate DIP.

If this becomes a thing, I'd like some way for my plugin(s) to still show to all users for discovery purposes. Users "window shop" for plugins a lot; I'd hazard a guess that a fair number of installs come from "oh, cool, there's a plugin that can do this?" rather than specifically seeking out a function. Blessed repos should be default-visible, but I suppose that's a discussion for that DIP instead of this one

2022-05-05 19:29 UTC, KazWolfe commented on text/0000-automated-build-and-submit-pipeline.md
> +When updating a plugin, the developer merely needs to update the `commit` for the metadata file, and make a PR. The previously mentioned steps will take place.
Mm, I suppose that could work but I'm not too big of a fan on that (though this comes from a "my own use case" model). Generally, I dislike the idea of changelogs being files in the repository as now that creates three different "views" of history:

* The `CHANGELOG.md` (or whatever) file that lives in the repo proper and will be displayed in Dalamud
* The commit messages themselves, as well as tag annotations (if any)
* The information available in GitHub Releases itself

Broadly speaking these should be *mostly* in sync, but some formatting/stylistic differences will appear. Text that renders well in GitHub Releases may not render as nicely in-game or in Discord. Information in one place may not necessarily apply to others.

Granted, this is already a problem, but it can be resolved through manual control of the release notes (e.g. just creating different copy-edits for the PR and the GH Releases page).

2022-05-06 22:04 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +When updating a plugin, the developer merely needs to update the `commit` for the metadata file, and make a PR. The previously mentioned steps will take place.
What would be your ideal solution? Something that comes to mind is taking the description of the PR, or a subset of that (e.g. the PR contains a special "changelog" section).

2022-05-06 22:08 UTC, philpax commented
> Would a developer be able to test the build process to make sure it works before PRing? One concern of mine is merging a PR and then the plugin build fails in the action. Perhaps we could provide a standalone action runnable through [act](https://github.com/nektos/act), or a Docker container.
> 
> ~also can we please make a cool dalamud logo ascii art for the script that'll build the plugins~

Fine by me! I'm also entirely fine letting people fail their builds on submission, failures happen all the time. Just need to make sure they're graceful :)

I'll make a note about making sure the action is compatible for local running...

2022-05-06 22:09 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +    "commit": "7ba9de4049066218f67e260e2c0f8ec0651ffed7"
Good catch. Separate folder, similar to how `DalamudPlugins` currently works:
```
main/plogonscript.json
testing/plogonscript.json
```

2022-05-07 01:37 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +When updating a plugin, the developer merely needs to update the `commit` for the metadata file, and make a PR. The previously mentioned steps will take place.
Decided to just add `changelog` to the submitted manifest. Seems simplest, and is nice and declarative.

2022-05-07 01:41 UTC, philpax commented
I've updated the DIP to address all of the feedback mentioned here, as well as discussion in Discord. I expect the proposed changes to the `csproj` to be a little controversial, but the rest should be more or less acceptable. Let me know what y'all think!

2022-05-07 01:53 UTC, NotAdam commented on text/0000-automated-build-and-submit-pipeline.md
> +- `net6`: Plugins compiled for the .NET 6 version of Dalamud, so that they can be tested for the migration.
`testing/net6` instead? `net6` by itself doesn't really mean anything by itself in terms of where it lives in the release pipeline

2022-05-07 01:53 UTC, NotAdam commented on text/0000-automated-build-and-submit-pipeline.md
> +        <TestingExclusive>True</TestingExclusive>
what's the point of this if it only exists on the testing branch? isn't this a process failure if it ends up on main?

2022-05-07 01:53 UTC, NotAdam commented on text/0000-automated-build-and-submit-pipeline.md
> +    - **Not every dev wants to use DalamudPackager**: they won't need to, but using it will make their life easier, as they will no longer need to maintain the JSON themselves, and what they build is
i thought people are just configuring some shit in the xml which is used by CI? why is there a json?

2022-05-07 02:14 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +- `net6`: Plugins compiled for the .NET 6 version of Dalamud, so that they can be tested for the migration.
I left it as a top-level folder to make it clear that there's a folder => channel mapping, but yeah that's not a bad idea. Will think about it.

2022-05-07 02:16 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +        <TestingExclusive>True</TestingExclusive>
Good question. I ported that over from the existing [JSON](https://github.com/Ottermandias/GatherBuddy/blob/main/GatherBuddy.json), but we can probably get rid of this. Only question is if we want the extra check to prevent deployment of a testing version into main; I don't really have any strong feelings about that.

2022-05-07 02:20 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +    - **Not every dev wants to use DalamudPackager**: they won't need to, but using it will make their life easier, as they will no longer need to maintain the JSON themselves, and what they build is
🥲 

We have a [JSON file that shares the name of the plugin](https://github.com/goatcorp/SamplePlugin/blob/master/Data/SamplePlugin.json) and it is populated with some basic information about the plugin. DalamudPackager takes that existing JSON, and combines it with information from the `csproj` regarding AssemblyVersion etc to create the final JSON, which looks like [this](https://github.com/Ottermandias/GatherBuddy/blob/main/GatherBuddy.json).

That final JSON is then manually uploaded, alongside the zip of the package, to `DalamudPlugins`. I find this to be pretty redundant (why is there a step to combine the JSON and csproj into another JSON instead of just sourcing all the information from csproj?), but people have built workflows around this and some people manually maintain the final JSON themselves...

There's a bit of a general reticence to use `DalamudPackager` as well. @Eternita-S might be able to talk about their reasons/workflow here.

2022-05-07 02:44 UTC, NotAdam commented on text/0000-automated-build-and-submit-pipeline.md
> +    - **Not every dev wants to use DalamudPackager**: they won't need to, but using it will make their life easier, as they will no longer need to maintain the JSON themselves, and what they build is
yeah okay, so the easy solution is to not use dalamudpackager and do it in a less shit way

sounds good to me 👍

2022-05-07 15:00 UTC, kalilistic commented
Should probably add @daemitus to this one too given his work on the existing github action.

2022-05-07 17:15 UTC, KazWolfe commented
As part of this process, we should add Actions to the PR process to verify that:

1. The plugin actually builds properly.
2. The resulting manifest contains all required fields (e.g. name, punchline, version)
3. The plugin passes a basic automated test suite (containing what? Signature validation? Security?)

2022-05-07 18:17 UTC, karashiiro commented
Oh yeah, I'm not sure if it's useful or not but I just remembered I had this <https://github.com/karashiiro/Dalamud-Checksummer/blob/main/Dalamud-Checksummer.ps1> that I was working on a while back.

2022-05-10 02:34 UTC, ayyaruq reviewed
Overall looks good, I have some nits with the user experience, and I think there's over-emphasis on things that are't fully defined. There's also some customisation decisions that don't make sense for a build service.

While I agree that a decentralised approach makes the most sense, I'm not sure forcing everything into a goatcorp repo is the way to do that. Consider a GHA plugin that can run directly in user repos and submits a manifest for review. This way the free build hours aren't shared across all users, you get more build concurrency, and if the actions are well made you can still enforce all the checking.

A separate "CD" process or whatever could then check the actual code before making the manifest public to users. I'd likely proxy the URLs to GH with a perma redirect tho, so users hit the CF fronted web server for the manifest and then download it from GH releases instead of wasting goatcorp bandwidth. The downside here is your GHA's need to be better, and it's slightly more iffy for non-GH users that would need some goatcorp repo to use instead. I expect some hybrid is likely the actual answer, or otherwise centralise it and try find a way to make builds not cost a fortune. More repos is likely not the answer tho, especially if it involves manually PRing what's essentially a version string bump. Just automate the PR outright.

2022-05-10 02:34 UTC, ayyaruq commented on text/0000-automated-build-and-submit-pipeline.md
> +The primary role of the action is to consume a plugin manifest, and produce an artifact that can be loaded by Dalamud, or be included within `DalamudPlugins`. `DalamudPlugins` will only be updated on
This is predicated on your `DalamudPlugins` repo being a good source of truth, which imo isn't necessarily the case, especially with multiple release streams. I think this also isn't clear with *where* the GHA build job runs. If it's in a single repo, the org will run into resource limits, and if it's not then you need all the overhead of setting up GHA to make PRs to other repos and handle crap like merging for conflicts.

2022-05-10 02:34 UTC, ayyaruq commented on text/0000-automated-build-and-submit-pipeline.md
> +The `csproj` file should describe how to build the plugin. There may be cursory automated checking of the `csproj` to ensure that it is not doing anything malicious, but the primary verification stra
You could likely use a bot for this. Something like PR goes up, it goes into a state of waiting for project config and manifest review, then an approved reviewer can post a comment like `/init-review pass` that the bot then triggers the GHA for and updates labels for state. Kinda meme, but there's enough open source things like this to quickly throw something together.

2022-05-10 02:34 UTC, ayyaruq commented on text/0000-automated-build-and-submit-pipeline.md
> +To encourage CI compatibility, as well as making it easier to test, a goatcorp-blessed GitHub Action will be made available that plugin developers can include as part of their repository. This action
I'd also update the various template repos to include this, and make sure they're actual GH templates. Prob mainly a note for @karashiiro if this goes ahead.

2022-05-10 02:34 UTC, ayyaruq commented on text/0000-automated-build-and-submit-pipeline.md
> +- **the turnaround time for plugin updates will be faster** due to the process being significantly simpler. A developer can make a change, commit it, and then use the GitHub web UI to open a PR to up
I don't think making a PR in the UI is a benefit, but it's also not required here. Could always have a separate goatcorp GHA in user-repos for GH users to trigger on new tags/releases and auto generate the PR. This also allows using tags which is generally a better idea than raw commit refs, provided they're not repointed.

2022-05-10 02:34 UTC, ayyaruq commented on text/0000-automated-build-and-submit-pipeline.md
> +- **users can be confident that plugins have been audited to some degree**; while most users do not directly care about this, someone _should_ care, because deploying malware to 100k people would suc
This is where a notary service is of value, it doesn't affect the security but it *does* verify the supply chain which is of value. You also get an audit trail of who reviewed what, and easier revocations.

2022-05-10 02:34 UTC, ayyaruq commented on text/0000-automated-build-and-submit-pipeline.md
> +Initial discussion proposed a web portal, likely in addition to existing goatcorp services, where developers could submit their plugins to be reviewed. While this would be nice to have, it's not real
There's value in a web portal, but this specific way of centralising things makes it much less useful. A more appropriate use of a web portal in this proposal would be for indexing the downloadable artefacts instead of users needing to hit up a git repo for the source of truth, they can't see the git stuff anyway in XL but it gives you a static source relative to one that can be manipulated.

2022-05-10 02:34 UTC, ayyaruq commented on text/0000-automated-build-and-submit-pipeline.md
> +An alternative design was proposed by [Ay](https://github.com/ayyaruq) where plugin developers, upon main repo approval, would be given keys exclusive to the plugin that could be used to sign future
The main bulk of my suggestion was actually notarising, not signing. Code signing says a plugin is built by a goatcorp trusted developer, it says nothing about the plugin or build process being safe. Notarising gives you an audit trail of who specifically did what so you can see the full data provenance of the artefact, *and you can revoke ones found to be bad after release* which is the important bit. While I do think some bits of this are more complex than this proposal, I think the workflow is simpler and the infra needed for notarising isn't particularly complex, hell I'd built it myself if wanted.

The key issue here is what the goal is. If you want to know a plugin has been built by an approved dev, code signing works. If you want a nicer build process, then the security components aren't really relevant. If you want to improve user trust, notarising works. Different solutions for different goals.

2022-05-10 02:34 UTC, ayyaruq commented on text/0000-automated-build-and-submit-pipeline.md
> +    - **Not every dev wants to use DalamudPackager**: they won't need to, but using it will make their life easier, as they will no longer need to maintain the JSON themselves, and what they build is
Using the name of the plugin in the manifest file is a bit iffy, just roll with `manifest.json` or whatever and be done with it. A consistent name means less faffing around with config handling and easier for newbie devs reading other repos for ideas.

2022-05-10 02:34 UTC, ayyaruq commented on text/0000-automated-build-and-submit-pipeline.md
> +    - **What about build-time dependencies that I rely on, but don't want goatcorp to build?** We have no immediate plans to support this. Unfortunately, this means our current answer is "build the d
Or... just have a separate step to pull them down?

2022-05-10 02:34 UTC, ayyaruq commented on text/0000-automated-build-and-submit-pipeline.md
> +  - This is pretty hard to verify when unsafe code is enabled, as all bets are off. This would be a relatively coarse check to make sure that there isn't anything _immediately_ suspect.
Realistically this will require some custom static analysis tooling. Not sure how hard this is to do, but it's likely the only way.

2022-05-10 05:23 UTC, KazWolfe commented on text/0000-automated-build-and-submit-pipeline.md
> +commit = "9ef08248497c7f9f1312e14c50650183ee365734882a655345fc06abdac511f1"
I'd tend to agree, but tags and branches are immutable. If we want to trace the lifecycle of plugin code to a specific and exact version, I think we'd have to use commits.

Otherwise, a malicious actor could create a tag `v1.0.1` with malicious code, wait for it to pass through review, and then force-push/retag to a clean code version. I'm unsure how much of a concern this would *realistically* be, but it feels like it could create a bit of a headache.

2022-05-10 07:04 UTC, ayyaruq commented on text/0000-automated-build-and-submit-pipeline.md
> +commit = "9ef08248497c7f9f1312e14c50650183ee365734882a655345fc06abdac511f1"
I don't think that's much of an issue. When new commits are pushed, GH will require updated approvals. As far as CI goes, you grab the ref from the tag so if the tag changes, so does the ref and it's no longer what was approved.

2022-05-10 23:48 UTC, kalilistic approved these changes

2022-05-10 23:57 UTC, ayyaruq commented
> I'll make a note about making sure the action is compatible for local running...

Generally stuff that relies on GitHub specific APIs (like cache) doesn't work in `act`, anything else should be gucci.

2022-05-14 00:17 UTC, kalilistic commented
Maybe I got excited and approved early. Looks like this is pending some cleanup by @philpax based on the additional comments.

2022-05-14 02:06 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +    - **Not every dev wants to use DalamudPackager**: they won't need to, but using it will make their life easier, as they will no longer need to maintain the JSON themselves, and what they build is
So, what we have now is a two-variant process:
- an initial `pluginname.json` that the dev fills with some basic information about their plugin
- DalamudPackager, or a very picky dev, then fills in that `pluginname.json` with the rest of the required information, most of which is sourced from the `csproj`

I think it's a bit silly that we have two versions of the same file, especially when the latter is much more clearly meant to be the result of an automated process (except, again, for those very picky devs with their own workflow)

That's why I'm thinking we can move the actual user-specified properties to the `csproj`, and then pull from that to generate the final manifest. Naming it `manifest.json` is totally fine by me, just depends on how much rework we do of the plugin loader.

2022-05-14 02:38 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +- `main`: The primary repository for Dalamud plugins, and what first-party plugin users will have access to. This is the most stringest to submit to, as it has the widest audience, but we should offe
lmao how did I do "stringest"? this is what happens when you write 4am DIPs. no opinion on the channel name, will change to `stable` unless anyone has very strong opinions

2022-05-14 02:40 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +Each folder contains files that correspond to a submitted plugin, which is what plugin developers will submit and update. The file will follow this structure (TOML):
I like TOML and think it's a perfectly acceptable fit for a currently-user-targeted configuration file, especially because it vastly constrains what's possible compared to YAML. JSON's _fine_ but is marginally more annoying to manually update.

Will stick with TOML unless someone else tells me that they simply cannot go on if it isn't JSON.

2022-05-14 02:41 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +commit = "9ef08248497c7f9f1312e14c50650183ee365734882a655345fc06abdac511f1"
I'm with Kaz here - I think it's much easier to reason about what's actually deployed if you have a fixed version being specified. I think the benefit of being able to look at a manifest and knowing exactly which version is in play outweighs someone PEBKACing an out-of-branch ref.

2022-05-14 02:42 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +location = "plugin"
Did think about this for a very brief moment and thought that `location` was nice and terse, but yeah you're probably right, will switch to `project_path`.

2022-05-14 02:45 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +This DIP also proposes moving all properties associated with `pluginname.json` into the project's `csproj`, and having the `pluginname.json` be generated by DalamudPackager using the information with
> Realistically most plugins do use a csproj, but definitely not all. 
What would you ("you" as in mystery plogon dev) use instead, and why? Is a non-standard configuration like that worth supporting?

`manifest.json` is fine by me though.

2022-05-14 02:46 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +        <IconUrl>https://raw.githubusercontent.com/Ottermandias/GatherBuddy/main/images/icon.png</IconUrl>
Not sure what the current situation with that is - probably worth doing, but I think that's out of scope for this DIP

2022-05-14 02:50 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +The primary role of the action is to consume a plugin manifest, and produce an artifact that can be loaded by Dalamud, or be included within `DalamudPlugins`. `DalamudPlugins` will only be updated on
> This is predicated on your DalamudPlugins repo being a good source of truth, which imo isn't necessarily the case, especially with multiple release streams. 

If it _isn't_ a good source of truth, what's the point of doing all of this?

> I think this also isn't clear with where the GHA build job runs. If it's in a single repo, the org will run into resource limits, and if it's not then you need all the overhead of setting up GHA to make PRs to other repos and handle crap like merging for conflicts.

Fair point. I thought it was reasonably clear that we'd be the ones building, either through GHA or our own build server, but I'll tweak the language to make that a bit more obvious once this round of feedback's locked in.

I'm still rather attached to building the plugins "ourselves"; I think it's conceptually the simplest model for both goatcorp and developers to get their heads around, and it gives us free reign in doing whatever kind of validation / post-processing that we want to do for first-party deployment. I don't think chipping in for unrestricted builds would be problematic if it got to that point.

2022-05-14 02:50 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +The `csproj` file should describe how to build the plugin. There may be cursory automated checking of the `csproj` to ensure that it is not doing anything malicious, but the primary verification stra
Yeah definitely, I'm most familiar with https://github.com/bors-ng/bors-ng myself

2022-05-14 02:52 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +- **the turnaround time for plugin updates will be faster** due to the process being significantly simpler. A developer can make a change, commit it, and then use the GitHub web UI to open a PR to up
Agree to disagree on the commit refs, as before. And yeah, plenty of automated solutions for this; I just wanted to make it clear that updating your plugin would end up being _significantly_ simpler than the current DalamudPackager-and-upload dance, and is something you could do from your phone if you were so inclined

2022-05-14 02:53 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +- **users can be confident that plugins have been audited to some degree**; while most users do not directly care about this, someone _should_ care, because deploying malware to 100k people would suc
True, but my gut feeling is that it's far too much effort for both developers and us compared to just building their code ourselves

2022-05-14 02:55 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +Initial discussion proposed a web portal, likely in addition to existing goatcorp services, where developers could submit their plugins to be reviewed. While this would be nice to have, it's not real
Yeah, a web portal's not super useful with the strategy described in this DIP. That being said, I refer to my previous comment - if we can't trust `DalamudPlugins`, who can we trust, and why are we doing this?

2022-05-14 02:56 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +An alternative design was proposed by [Ay](https://github.com/ayyaruq) where plugin developers, upon main repo approval, would be given keys exclusive to the plugin that could be used to sign future
Yes, sorry, I've the unfortunate tendency to mix those up. I'll update the wording on the next pass and try to better communicate what you were proposing.

2022-05-14 02:58 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +    - **What about build-time dependencies that I rely on, but don't want goatcorp to build?** We have no immediate plans to support this. Unfortunately, this means our current answer is "build the d
So this is in reference to something @KazWolfe brought up - XIVDeck has a JavaScript component that's built to be deployed to the Stream Deck, and may be provided by the plugin, but it's not part of the plugin itself. The concrete concern is that they did not want goatcorp to build the JS (which is in the same repo) because it's out of our purview, but at the same time, they wanted that JS to be available as a consumable artifact for the plugin.

Given that that's kind of annoying to support, I'm handballing it here by saying "build it yourself ahead of time within the repo". We can figure something out later if it ends up being more of a problem.

2022-05-14 02:59 UTC, philpax commented on text/0000-automated-build-and-submit-pipeline.md
> +  - This is pretty hard to verify when unsafe code is enabled, as all bets are off. This would be a relatively coarse check to make sure that there isn't anything _immediately_ suspect.
It's not too bad - @goaaats had a look at how S&box's solution works, and it basically just runs Roslyn over the codebase and scans over the resulting semantic information for naughties. Can add this whenever, I think

2022-05-15 10:44 UTC, goaaats commented on text/0000-automated-build-and-submit-pipeline.md
> +- `net6`: Plugins compiled for the .NET 6 version of Dalamud, so that they can be tested for the migration.
I like the `testing/branch` scheme, makes sense to me

2022-05-15 10:44 UTC, goaaats commented on text/0000-automated-build-and-submit-pipeline.md
> +Each folder contains files that correspond to a submitted plugin, which is what plugin developers will submit and update. The file will follow this structure (TOML):
I don't mind it either way - if we go with yaml, we have automatic support for json. I'm fine with TOML as well. In the end, the serializer we use probably supports both so I don't see why we can't offer both down the road, might just get annoying re: linting

2022-05-15 10:44 UTC, goaaats commented on text/0000-automated-build-and-submit-pipeline.md
> +        <IconUrl>https://raw.githubusercontent.com/Ottermandias/GatherBuddy/main/images/icon.png</IconUrl>
At the moment:
* Plugins on the main repo are ALWAYS loaded from the GitHub repo, the links in the manifest are completely ignored
* Plugins on the third party repo have their icons loaded from the manifest-provided links

This was a compromise we agreed upon when implementing this feature. I definitely want to avoid having regular Dalamud users leak accesses/their IPs to plugin-specified servers just by scrolling the installer, be it by having a media proxy or doing what we do right now(preferably).

2022-05-15 10:44 UTC, goaaats commented on text/0000-automated-build-and-submit-pipeline.md
> +  - This is pretty hard to verify when unsafe code is enabled, as all bets are off. This would be a relatively coarse check to make sure that there isn't anything _immediately_ suspect.
Note that checking for actual `unsafe` blocks is a pain in the ass, the only way to do it reliably is at compile time where you just don't turn them on. That would mean compiling it ourself, but then you can just pull in unsafe libraries from nuget.

I don't think we should worry about this right now. All discussion of security models for us has always resulted in too many limitations on plugin devs, e.g. no nuget, no unsafe, limited std lib - I think for now, without a lot of work, that ship has sort of sailed.

This DIP should first and foremost be about reviewability, IMO - the plugin team should be able to make sure that the ref specified is what produces the binary, being able to track changes, with an additional focus on dev experience.

2022-05-15 10:47 UTC, goaaats commented on text/0000-automated-build-and-submit-pipeline.md
> +This DIP also proposes moving all properties associated with `pluginname.json` into the project's `csproj`, and having the `pluginname.json` be generated by DalamudPackager using the information with
`pluginname.json` is stupid and should go, so `manifest.json` is fine by me.

2022-05-24 13:12 UTC, philpax commented
Just updated with latest round of feedback. Instituting informal RFC closure in a week's time, so the 31st. Get your feedback in now!

2022-05-24 16:10 UTC, KazWolfe commented on text/0000-automated-build-and-submit-pipeline.md
> +        <IconUrl>https://raw.githubusercontent.com/Ottermandias/GatherBuddy/main/images/icon.png</IconUrl>
Another vote in favor of keeping things as-is; icons being stored alongside the rest of the "app store" entry makes sense for mainline plugins. 

I'm not a huge fan of hardcoding different behavior for the mainline repo though -- would it be possible to always read `IconUrl` but then have the mainline `pluginmaster.json` always point to our own GitHub-controlled assets? We could then alter the build-time behavior to either download the image from the plugin-provided IconUrl or use the embedded icon at a well-known path.

Third-party repos are third-party repos; there's no way to really prevent IP leakage there without us *also* media-proxying actual plugins which opens a whole can of worms.

2022-05-24 16:12 UTC, goaaats approved these changes

2022-05-24 16:18 UTC, karashiiro commented
DIP number in the filename? Looks like it's still 0000.

2022-05-27 11:21 UTC, philpax commented
goat raised the very important issue of ensuring that only the right people get to submit manifest updates for their plugins. Still discussing best way to do that, but no-merge until that's in the DIP...

2022-05-28 01:36 UTC, NotAdam commented
just pull the userid from the gh api?

2022-05-28 06:06 UTC, philpax commented
> just pull the userid from the gh api?

How do you know which user ids are valid, especially for multi-contributor projects?

Anyhow, the solution I've settled on for now is to let people specify usernames for owners in the manifest they submit, and the pre-merge hook will just replace the usernames with IDs + username comment. Should handle changing usernames + future access control relatively easily, and we can always change it if it doesn't work.

Just need to write it up...

2022-05-29 08:31 UTC, ascclemens commented on text/17-automated-build-and-submit-pipeline.md
> +    707827, // Philpax
This is the smallest nit possible, but if this is going to be a guide, it should probably have the proper comment syntax. `#` instead of `//`.

2022-05-29 17:16 UTC, NotNite commented on text/17-automated-build-and-submit-pipeline.md
> +- Repo-Relevant Issue: [goatcorp/dalamud#0000](https://github.com/goatcorp/dalamud/issues/0000)
As I said on #18, are we keeping this or removing it (Repo-Relevant Issue)?

2022-05-29 17:16 UTC, NotNite commented on text/17-automated-build-and-submit-pipeline.md
> +    707827, // Philpax
As Anna said above, comment here should also be `#`.

2022-05-29 17:16 UTC, NotNite commented on text/17-automated-build-and-submit-pipeline.md
> +        <IconUrl>https://raw.githubusercontent.com/Ottermandias/GatherBuddy/main/images/icon.png</IconUrl>
Not sure where this was said (Discord?), are we going to whitelist this URL?

2022-05-29 17:16 UTC, NotNite commented on text/17-automated-build-and-submit-pipeline.md
> +This will require all first-party plugin developers to abide by a common project structure that is amenable to being built by CI, and for the code of their plugins to be open-source. The latter is al
Are the Sonar devs fine with this?

2022-05-29 18:22 UTC, philpax commented on text/17-automated-build-and-submit-pipeline.md
> +- Repo-Relevant Issue: [goatcorp/dalamud#0000](https://github.com/goatcorp/dalamud/issues/0000)
I think the best play here is to create a milestone to track the issues/tasks this will spawn, and to update the link here to point to that milestone.

2022-05-29 18:24 UTC, wolfcomp commented
Just gonna quickly comment, is it possible to maybe extend the automated pipeline to be a sort of plug and compile GitHub CI/CD system instead of locked to a specific NuGet package is required. That would require a specific file output for the upload instead of a specific build system. This would possibly take a little longer to make, but would open up the gates a little for how many drawbacks there are going to be otherwise being locked to one specific NuGet package. 

*Making this comment because DalamudPackager errors on my system complaining about some files missing when it's not missing.*

2022-05-29 18:27 UTC, philpax commented on text/17-automated-build-and-submit-pipeline.md
> +        <IconUrl>https://raw.githubusercontent.com/Ottermandias/GatherBuddy/main/images/icon.png</IconUrl>
I think this is where that discussion happened: https://github.com/goatcorp/DIPs/pull/17#discussion_r868725530

Seems like we already have an OK solution here, but it's something we can revisit later.

2022-05-29 18:58 UTC, lmcintyre commented
> Just gonna quickly comment, is it possible to maybe extend the automated pipeline to be a sort of plug and compile GitHub CI/CD system instead of locked to a specific NuGet package is required. That would require a specific file output for the upload instead of a specific build system. This would possibly take a little longer to make, but would open up the gates a little for how many drawbacks there are going to be otherwise being locked to one specific NuGet package. 
> 
> *Making this comment because DalamudPackager errors on my system complaining about some files missing when it's not missing.*

I would assume this should be something to look into (more descriptive errors) in DalamudPackager rather than rethinking the process. There is definitely a file missing in your case - it's just extremely difficult to determine *where*, because the error message just says that it couldn't find a file.

2022-05-29 19:05 UTC, wolfcomp commented
> > Just gonna quickly comment, is it possible to maybe extend the automated pipeline to be a sort of plug and compile GitHub CI/CD system instead of locked to a specific NuGet package is required. That would require a specific file output for the upload instead of a specific build system. This would possibly take a little longer to make, but would open up the gates a little for how many drawbacks there are going to be otherwise being locked to one specific NuGet package.
> > _Making this comment because DalamudPackager errors on my system complaining about some files missing when it's not missing._
> 
> I would assume this should be something to look into (more descriptive errors) in DalamudPackager rather than rethinking the process. There is definitely a file missing in your case - it's just extremely difficult to determine _where_, because the error message just says that it couldn't find a file.
The error was in an outdated structure of [SamplePlugin](https://github.com/goatcorp/SamplePlugin/) that was fixed with [#12](https://github.com/goatcorp/SamplePlugin/pull/12) that I followed to how I set up the project.

2022-05-29 19:10 UTC, philpax commented
Yup, we sorted out Wolf's issue on the Discord (thanks for pointing it out!) Wolf's mentioned that they're happy with this now that their issue's been fixed 👍 

As I mentioned on the Discord, my preference is to make the happy path trouble-free than to provide ways off the path. Happy to revisit once we get some more experience, though!

2022-05-29 19:25 UTC, rreminy commented on text/17-automated-build-and-submit-pipeline.md
> +This will require all first-party plugin developers to abide by a common project structure that is amenable to being built by CI, and for the code of their plugins to be open-source. The latter is al
As discussed here: https://discord.com/channels/581875019861328007/972311484782755870/980537973051375677

We been recently under heavy fire recently after we expanded to CN and I'd rather not open source Sonar as that will make it far easier for Sonar to be reverse engineered.

We banned the offending users however it was an arduous process as it was difficult to identify them and they were bypassing the only identifier at the time. We banned them by IP addresses but they were using multiple VPN services which made this process difficult. We banned multiple VPN services as a result. The process of identification has been made more robust since then, of which I cannot provide the details here.

I did point out as well that the build process is complicated as multiple binaries are built then merged. I can provide further details if needed. `SonarPlugin.dll` is the final target of the build process, being strictly essentially a loader as it takes the `AssemblyLoadContext` to load the embedded binaries and start/stop Sonar.

While it is true that its easy to decompile due to the nature of how .NET works, it still does provide a strong barrier for reverse engineering. Decompiled source has no comments or leads helping them understand how Sonar works on the inside. In addition, simply decompiling `SonarPlugin.dll` in itself will only get you the loader.

I'm alright with providing a secret to be used for the purpose of building Sonar with the new process, or continue being the exception for the time being.

2022-05-29 20:01 UTC, philpax commented on text/17-automated-build-and-submit-pipeline.md
> +This will require all first-party plugin developers to abide by a common project structure that is amenable to being built by CI, and for the code of their plugins to be open-source. The latter is al
Yep - up to goat for final approval, but my thoughts on this are that we should kick the can down the road for now and let Sonar continue to merge directly to DalamudPlugins for now. We can figure something out as we get more experience with the overall pipeline.

2022-05-31 09:53 UTC, ascclemens commented on text/17-automated-build-and-submit-pipeline.md
> +Developers will be encouraged to add a conditional step that will not be run on the CI to their `csproj` to run DalamudPackager. In this step, it will be running in a mode where it will output a gene
DalamudPackager will need to be changed if it's really meant that developers will be adding this step to their `csproj`. As can be seen [here](https://github.com/goatcorp/DalamudPackager/blob/fab64d4/DalamudPackager/build/DalamudPackager.targets), DP has default settings when the `targets` file is not present, as is common with dependencies that add build steps. If it's intended to change this behaviour, developers who rely on DP's default build steps will have to add them manually instead.

Furthermore, DP could instead have its defaults changed to automatically ignore CI builds, which is probably a better solution.

2022-05-31 17:45 UTC, rreminy commented on text/17-automated-build-and-submit-pipeline.md
> +This will require all first-party plugin developers to abide by a common project structure that is amenable to being built by CI, and for the code of their plugins to be open-source. The latter is al
@goaaats Before the merge happens, do you approve to let Sonar merge directly to DalamudPlugins manually for the time being?

2022-05-31 18:12 UTC, goaaats commented on text/17-automated-build-and-submit-pipeline.md
> +This will require all first-party plugin developers to abide by a common project structure that is amenable to being built by CI, and for the code of their plugins to be open-source. The latter is al
@rreminy Yes, that's okay for now. We'll figure something out when the system is up and running, which will be quite a while out.

2022-05-31 18:46 UTC, merged