WIP: Formal subteams
goatcorp/DIPs pull request #18
Opened 2022-05-03 09:19 UTC by philpax

Very rough proposal. Need to better select people for each subteam, and answer the unresolved questions.

2022-05-03 11:52 UTC, kalilistic commented on text/0000-formal-subteams.md
> +- **Documentation**: creation, maintenance and improvement of goatcorp-related documentation, including the FAQs, support guides, and developer documentation.
DIPs and SamplePlugin probably fit well here for now. Not sure worth their own category yet.

2022-05-03 11:52 UTC, kalilistic commented on text/0000-formal-subteams.md
> +- **Linux**: ???
Franz seems active in Linux too - not sure who the other usual suspects are though.

2022-05-03 11:52 UTC, kalilistic commented on text/0000-formal-subteams.md
> +- Are these the only subteams we want?
This seems like a good start.

2022-05-03 11:52 UTC, kalilistic commented on text/0000-formal-subteams.md
> +- Do we want formal leaders for each subteam?
Maybe overkill for now, can start simpler.

2022-05-03 16:33 UTC, philpax commented on text/0000-formal-subteams.md
> +- **Linux**: ???
We have a few new people with the xlcore work - not sure if we want to bring them onside. @goaaats ?

2022-05-03 16:33 UTC, philpax commented on text/0000-formal-subteams.md
> +- Do we want formal leaders for each subteam?
The main benefit would be so that other teams/people have a single point of contact, instead of "reach out to anyone in the team" - but I agree that we can probably leave it as is and see how it works out

2022-05-03 16:36 UTC, kalilistic commented on text/0000-formal-subteams.md
> +- **Documentation**: creation, maintenance and improvement of goatcorp-related documentation, including the FAQs, support guides, and developer documentation.
Not just the Simple Plugin... but I think there were early attempts at a plugin CLI that would be kind of neat to expand.

2022-05-05 10:59 UTC, ayyaruq commented on text/0000-formal-subteams.md
> +- Are these the only subteams we want?
I'd maybe reconsider documentation as it's own team. Nobody likes writing docs and by shunting it into containment it's likely to naturally drift behind the codebase. I think it'd be better to have some good docs patterns/templates and have each subteam maintain their respective docs inline.

Also, I realise mac users aren't a large pool but there seems enough of them that it might be worth having a team with say Franz just to direct questions to when they do come up.

2022-05-05 12:13 UTC, kalilistic commented
@philpax maybe @karashiiro's callout on issue house keeping commenting could be added as a sub-team task. https://github.com/goatcorp/DIPs/issues/21

2022-05-05 19:34 UTC, philpax commented on text/0000-formal-subteams.md
> +- Are these the only subteams we want?
> I'd maybe reconsider documentation as it's own team. Nobody likes writing docs and by shunting it into containment it's likely to naturally drift behind the codebase. I think it'd be better to have some good docs patterns/templates and have each subteam maintain their respective docs inline.

I agree for code documentation, but the subteam here (as I envision it) is for documentation outside of the code, like the FAQs etc. Might be better described as "Developer Relations" or something?

> Also, I realise mac users aren't a large pool but there seems enough of them that it might be worth having a team with say Franz just to direct questions to when they do come up.

No opposition from me. @reiichi001 ?

> We should create a separate DIP for documentation patterns, describing what forms of documentation should be kept and where. Information on how things need to be updated for each patch seems like a crucial part of that, along with project structure etc.

+1

2022-05-05 19:41 UTC, reiichi001 commented on text/0000-formal-subteams.md
> +- Are these the only subteams we want?
For the most part, the XIVonMac team handles the bulk of macOS users and have a dedicated support discord as there are certain wine quirks on macOS that they're more familiar with. (Ex: Current MoltenVK on Intel GPUs is broken).

I'm happy to bridge the communities, as they're also making use of Franzbot as needed to help with FAQs, but we can likely defer to them for many macOS-specific questions. @marzent is their lead dev and I'd defer to their opinions for macOS.

2022-05-05 19:43 UTC, philpax commented on text/0000-formal-subteams.md
> +- **Documentation**: creation, maintenance and improvement of goatcorp-related documentation, including the FAQs, support guides, and developer documentation.
> Not just the Sample Plugin... but I think there were early attempts at a plugin CLI that would be kind of neat to expand.

That sounds pretty neat, can you make an issue for it?

2022-05-05 19:43 UTC, philpax commented
> @philpax maybe @karashiiro's callout on issue house keeping commenting could be added as a sub-team task. #21

Mmm, maybe under documentation or community?

2022-05-05 22:32 UTC, kalilistic commented on text/0000-formal-subteams.md
> +- **Documentation**: creation, maintenance and improvement of goatcorp-related documentation, including the FAQs, support guides, and developer documentation.
> > Not just the Sample Plugin... but I think there were early attempts at a plugin CLI that would be kind of neat to expand.
> 
> That sounds pretty neat, can you make an issue for it?

A separate pre-dip for a dip?

2022-05-06 00:15 UTC, philpax commented on text/0000-formal-subteams.md
> +- **Documentation**: creation, maintenance and improvement of goatcorp-related documentation, including the FAQs, support guides, and developer documentation.
Yeah, just make an issue with a few brief notes and we can use that to write up a proper DIP later

2022-05-06 02:18 UTC, philpax commented on text/0000-formal-subteams.md
> +- Are these the only subteams we want?
Alright, no Mac team for now. We can come back to that later if we need to.

2022-05-06 02:45 UTC, philpax commented
I've addressed the initial round of feedback. We still have a few open concerns:
- Who should be in the Linux team? Question for goat and co, I'm not across the bulk of the work there
- What kind of permissions should a subteam member have? Probably worth assigning these per-team, so that XL/Dm teams can commit to the repos, while Community have free reign to prune issues etc

2022-05-06 23:47 UTC, philpax commented on text/0000-formal-subteams.md
> +- **Documentation**: creation, maintenance and improvement of goatcorp-related documentation, including the FAQs, support guides, and developer documentation.
#26

2022-05-07 01:49 UTC, philpax commented
Was writing up my reply to #22, and it occurred to me that we could potentially benefit from a reverse engineering subteam if our reversers are interested. This would allow developers to know who to ask to find something / for help reversing, and if a variant of #22 is actioned, a dedicated team can be responsible for helping integrate people's reversed findings into ClientStructs etc.

2022-05-09 03:49 UTC, ayyaruq commented on text/0000-formal-subteams.md
> +- Are these the only subteams we want?
> I agree for code documentation, but the subteam here (as I envision it) is for documentation outside of the code, like the FAQs etc. Might be better described as "Developer Relations" or something?

This sounds reasonable to me, dunno about the team name, work uses DevEx (Developer Experience) which sucks so anything better than that is good by me.

2022-05-12 22:17 UTC, Helios747 commented on text/0000-formal-subteams.md
> +- **Linux**: ???
I'll help with Linux support / testing if you're looking for warm bodies. I'm a regular Linux junkie.

Not sure I want to commit the time to actually contributing code rn though.

2022-05-14 02:26 UTC, philpax commented
sorry to get on your goat @goaaats but your eyes would be appreciated on this soon

2022-05-15 08:23 UTC, goaaats commented
> I've addressed the initial round of feedback. We still have a few open concerns:
> 
> * Who should be in the Linux team? Question for goat and co, I'm not across the bulk of the work there
> * What kind of permissions should a subteam member have? Probably worth assigning these per-team, so that XL/Dm teams can commit to the repos, while Community have free reign to prune issues etc

I imagine having package mantainers in the Linux/Unix team would be a good choice - at the moment that's me, ashkitten, Caliel666, Centzilius. Marzent is from XoM and helps with wine. Dormanil is an user and helps out with xlcore stuff.

2022-05-15 08:31 UTC, goaaats requested changes

2022-05-15 08:31 UTC, goaaats commented on text/0000-formal-subteams.md
> +- **Linux**: ensures that XIVLauncher and Dalamud work well and/or conveniently on Linux, including the Steam Deck
Rename the Linux team to Unix? The XoM dev has been helping a lot with xlcore and fixed it up for mac support, we should be inclusive of that.

2022-05-15 08:31 UTC, goaaats commented on text/0000-formal-subteams.md
> +- **Linux**: ???
Mentioned in the other post: ashkitten, Caliel666, Centzilius. Marzent is from XoM and helps with wine. Dormanil is an user and helps out with xlcore stuff. Helios747 just volunteered.

These are the people that I just came up with off the cuff.

2022-05-15 08:31 UTC, goaaats commented on text/0000-formal-subteams.md
> +- **Plugin Approval**: goat, Franz, Caraxi, ???
\+ @karashiiro if they still want in, I think we should have a 4th person either way

2022-05-15 08:31 UTC, goaaats commented on text/0000-formal-subteams.md
> +The initial members of each subteam will be as follows:
I think we should make sure that the people listed here want to actually be listed and are in the right category, either way - if you want, I can do that.

2022-05-15 08:31 UTC, goaaats commented on text/0000-formal-subteams.md
> +Aspects of the goatcorp ecosystem will be entrusted to people who aren't goat, which could potentially mean the wrong call is made with goatcorp permissions. Hopefully we pick the right people!
I'd maybe add as a risk that people outside of the "circle" might not feel compelled to contribute as they might feel that there is a "closed community". This is already addressed in the future possibilities section, but I thought it would be good to highlight.

2022-05-15 08:31 UTC, goaaats commented on text/0000-formal-subteams.md
> +  - Initial consensus: some developer relations-related responsibilities as well, but code documentation remains with the people writing the code
I think we should write down what this team does if anyone's bored at some point, just so that there's no confusion - is it updating FAQs, documenting code, etc?

2022-05-15 10:59 UTC, goaaats requested changes

2022-05-15 10:59 UTC, goaaats commented on text/0000-formal-subteams.md
> +- **Community**: Franz, kal, ???
Franz explicitly mentioned to me that he doesn't want to do much actual community work/moderation anymore as he doesn't have the motivation/energy anymore. What does this role actually entail? @reiichi001 would you still be up for being listed?

2022-05-15 22:57 UTC, Zi-SH commented on text/0000-formal-subteams.md
> +- **Linux**: ???
If you'd like more hands I'd happily be on the Linux subteam as well. Quite familiar with Linux and have been helping out in the Discord.

2022-05-16 15:26 UTC, goaaats commented
We've just identified a need for a "support" subteam that manages support channels/tools, is there a space for this? With Franz + Nite + me for now, I guess. Maybe this can be combined with community?

2022-05-16 16:32 UTC, kalilistic commented on text/0000-formal-subteams.md
> +- **Community**: Franz, kal, ???
I'm not sure how this splits by teams... I'd be personally interested in staying involved with suggestions and helping out with the sample plugin/cli.

2022-05-22 10:39 UTC, philpax commented
I'm going to institute an informal final comment period. If there's no major objections, I'll merge this in a week's time (the 29th) and we can action it by creating the relevant GitHub teams/Discord roles, setting up permissions, and unblocking the other PRs.

2022-05-22 10:39 UTC, philpax commented on text/0000-formal-subteams.md
> +The initial members of each subteam will be as follows:
I'd appreciate that if you could! If you're okay with the members as listed, reach out to them, confirm they're okay, and we can lock them in 🙏

2022-05-22 11:17 UTC, marzent commented on text/0000-formal-subteams.md
> +The initial members of each subteam will be as follows:
Although having been involved with all the *nix stuff, I also quite like working on the launcher side of things if people are still wanted there.

2022-05-24 16:18 UTC, karashiiro commented
Filename DIP number?

2022-05-24 21:49 UTC, ArcaneDisgea commented on text/0000-formal-subteams.md
> +We could potentially develop policies around how to join a subteam, so that people interested in participating know how to start.
I have a prototype discord bot in a private repo that does have an online form that can be filled out as an application that then creates a thread in a discord channel and can ping relevant members to discuss said application/applicant. Not sure if you all would find that useful or if it's too much.

2022-05-29 16:46 UTC, NotNite approved these changes

2022-05-29 16:48 UTC, NotNite commented on text/18-formal-subteams.md
> +- Repo-Relevant Issue: [goatcorp/dalamud#0000](https://github.com/goatcorp/dalamud/issues/0000)
Scratch the last review, missed this - are we keeping the "Repo-Relevant Issue" if there's no issue? Or should it be removed?

2022-05-29 16:49 UTC, karashiiro approved these changes

2022-05-29 19:30 UTC, merged

2022-05-29 19:46 UTC, philpax commented
Congratulations on the first DIP, everyone! goat's not feeling well today so we won't action it immediately, but we'll get the ball rolling soon 🎉